{% set name = "tsl_hopscotch_map" %}
{% set version = "2.2.1" %}
{% set sha256 = "73e301925e1418c5ed930ef37ebdcab2c395a6d1bdaf5a012034bb75307d33f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/Tessil/hopscotch-map/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/hopscotch_map.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_hopscotch_map/tsl_hopscotch_mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_hopscotch_map/tsl_hopscotch_mapConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tsl\hopscotch_map.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_hopscotch_mapConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_hopscotch_mapConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Tessil/hopscotch-map
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ hash map and hash set using hopscotch hashing'
  description: 'C++ hash map and hash set using hopscotch hashing'
  doc_url: https://tessil.github.io/hopscotch-map/
  dev_url: https://github.com/Tessil/hopscotch-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
