{% set name = "tsl_hopscotch_map" %}
{% set version = "2.3.0" %}
{% set sha256 = "a59d65b552dc7682521989842418c92257147f5068152b5af50e917892ad9317" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Tessil/hopscotch-map/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/tsl  # [unix]
    - test -f ${PREFIX}/include/tsl/hopscotch_map.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_hopscotch_map/tsl_hopscotch_mapConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/tsl_hopscotch_map/tsl_hopscotch_mapConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\tsl\hopscotch_map.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_hopscotch_mapConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\tsl_hopscotch_mapConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Tessil/hopscotch-map
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: C++ hash map and hash set using hopscotch hashing
  description: C++ hash map and hash set using hopscotch hashing
  doc_url: https://tessil.github.io/hopscotch-map/
  dev_url: https://github.com/Tessil/hopscotch-map

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
