appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: uxqo2j+iJpuoyXcTMUlm4nKPCdUN+ib63AbcM5hf2L8OhdDwqipHp7mCDvmRYO8vBdQxGtMY1jnMCOt+hJNo6H2QsPfYQxokagAtXodb24+K0FwYg8sJRDdQeAAZeHrgpL2muTjCTzAx+mAvn8iF1T9MU2LGkUc5aFT5t+snCTC7Jw+57fs87FFRXCTMGFP3VYdpm+zfTQ693371UgJdn0+r6ALpSVlyvSjEsCz/5XVbdZJ7933MFslGCXoWUhBAZ+gZIE80mwTf008UAZpu7DcNwo2COk8BJnuiQ2US/dG4oL37PlBWamV0W6CxCzh+GY96BzQQRSFY2VNHUWnIsv+Yrnb7BHaNVTyuBqPMBDaWdV/HorLJX6nekqGlWrKvtz6vD+HRakPkspb69RqeL+WKuf1MRyA0WRCUTlSFFSH+UkflWunOD7hVh/WCr2/IhMAqY5Q+ImEuKXbaaqdKAJTdoF1sZC6FiD6pOyi9Iyhbf9Ss+Ph6ICUthmd/pkddAP62PLUhcPGDAZxrysIrZMSeV88dC9QKPL+Mgu9d191FDqe87nZ25/C5YJ3ljlkeQ6MQbM+usJmNhatG78546HiMjdNfz7rGnOG2KdgHj8RXICl4aoFzHo+YNPkEn01ZysZWHVu+fGspOJ9UHFS9laY5oaZznc7I/T89sFfgUBw=}
provider:
  win: azure
